#!/bin/csh

# Convert text
echo "---------------- Text and Binary Files -----------------"
unzip -a xevilsrc.zip -x win32/res/\*.bmp
# Don't convert CRLF
echo "---------------- Binary Files -----------------"
unzip -b xevilsrc.zip win32/res/\*.bmp

