//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by xevil.rc
//
#define IDS_NETHELPURL                  1
#define IDD_ABOUTBOX                    100
#define IDB_CHOPPERBOY0                 101
#define IDB_CHOPPERBOY0B                102
#define IDB_CHOPPERBOY1B                103
#define IDB_CHOPPERBOY1                 104
#define IDB_CHOPPERBOY2                 105
#define IDB_CHOPPERBOY3                 108
#define IDB_CHOPPERBOY4                 109
#define IDB_CHOPPERBOY5                 110
#define IDB_CHOPPERBOY_DEAD             111
#define ID_STATUSBAR                    111
#define IDB_NINJA3B                     124
#define IDB_NINJA3                      125
#define IDR_MAINFRAME                   128
#define IDR_XEVILTYPE                   129
#define IDB_WALL                        130
#define IDB_UNKNOWN                     132
#define IDB_DOOR1                       133
#define IDB_DOOR2                       134
#define IDB_LADDER                      135
#define IDB_EMPTY                       136
#define IDB_SQUANCH                     137
#define IDB_HISQUANCH                   137
#define IDB_UPDOWN                      138
#define IDB_OUTSIDE                     139
#define IDB_TEXTSQUARE                  140
#define IDB_ALIEN0                      141
#define IDB_ALIEN0B                     142
#define IDB_ALIEN1                      143
#define IDB_ALIEN1B                     144
#define IDB_ALIEN2                      145
#define IDB_ALIEN3                      146
#define IDB_ALIEN4                      147
#define IDB_ALIEN5                      148
#define IDB_ALIEN8                      149
#define IDB_ALIEN7                      150
#define IDB_ALIEN10                     151
#define IDB_ALIEN11                     152
#define IDB_ALIEN14                     153
#define IDB_ALIEN13                     154
#define IDB_ALIEN16                     155
#define IDB_ALIEN17                     156
#define IDB_ALIEN18                     157
#define IDB_ALIEN7B                     158
#define IDB_ALIEN8B                     159
#define IDB_ALIEN10B                    160
#define IDB_ALIEN11B                    161
#define IDB_ALIEN13B                    162
#define IDB_ALIEN14B                    163
#define IDB_ALIEN16B                    164
#define IDB_ALIEN17B                    165
#define IDB_ALIEN18B                    166
#define IDB_ALIENDEAD                   167
#define ID_TIMER                        169
#define ID_DISCONNECTSERVER             170
#define ID_STOPSERVER                   171
#define IDC_SETTINGS                    172
#define IDR_XEVIL                       173
#define IDC_STARTSERVER                 173
#define IDC_XEVIL                       174
#define IDR_XEVIL_SMALL                 174
#define IDC_STOPSERVER                  174
#define IDC_XEVIL_SERVER                175
#define IDC_DISPLAY                     175
#define IDC_MESSAGEDISPLAY              176
#define IDC_XEVIL3                      177
#define ID_MIDI1                        178
#define IDB_FTHROWER                    214
#define IDB_FROGGUN                     254
#define IDB_GRENADES                    256
#define IDB_LANCER                      258
#define IDB_LAUNCHER                    260
#define IDB_MGUN                        262
#define IDB_PISTOL                      264
#define IDB_SHOTGUN                     266
#define IDB_STARS                       268
#define IDB_SWAPPER                     270
#define IDB_WALKER0                     272
#define IDB_WALKER0B                    273
#define IDB_WALKER2                     274
#define IDB_WALKER2B                    275
#define IDB_WALKER3B                    276
#define IDB_WALKER3                     277
#define IDB_WALKER4                     278
#define IDB_WALKER5                     279
#define IDB_WALKER11                    280
#define IDB_WALKER10                    281
#define IDB_WALKER1D                    289
#define IDB_WALKER1C                    291
#define IDB_WALKER1B                    293
#define IDB_WALKER1                     297
#define IDB_WALKER0D                    299
#define IDB_WALKER0C                    301
#define IDB_WALKER_DEAD                 309
#define IDB_LASER_VERT                  311
#define IDB_SHELL                       314
#define IDB_LANCE_HORZ                  316
#define IDB_LANCE_VERT                  318
#define IDB_HOME                        320
#define IDB_ALTAR0                      322
#define IDB_ALTAR1                      323
#define IDB_BOMB5                       327
#define IDB_BOMB4                       330
#define IDB_BOMB3                       333
#define IDB_BOMB2                       336
#define IDB_BOMB1                       339
#define IDB_BOMB0                       342
#define IDB_BOMB6                       344
#define IDB_CLOAK                       345
#define IDB_DOPPEL                      347
#define IDB_EGG                         349
#define IDB_EGG_OPEN                    352
#define IDB_ENFORCER_DEAD               354
#define IDB_ENFORCER5                   356
#define IDB_ENFORCER1B                  358
#define IDB_ENFORCER1                   360
#define IDB_ENFORCER1D                  360
#define IDB_ENFORCER0B                  362
#define IDB_ENFORCER0                   364
#define IDB_ENFORCER0D                  364
#define IDB_FIREDEMON5B                 366
#define IDB_FIREDEMON5                  368
#define IDB_FIREDEMON4                  370
#define IDB_FIREDEMON3                  372
#define IDB_FIREDEMON22                 375
#define IDB_FIREDEMON21                 377
#define IDB_FIREDEMON2                  378
#define IDB_FIREDEMON1B                 380
#define IDB_FIREDEMON1                  382
#define IDB_FIREDEMON0B                 384
#define IDB_FIREDEMON0                  386
#define IDB_TRANSMOGIFIER               388
#define IDB_FIREDEMON_DEAD              390
#define IDR_XEVILMENU                   390
#define IDD_OPTIONS                     392
#define IDB_SWAP_SHELL                  473
#define IDB_SWAP_SHELLB                 475
#define IDB_WEIGHT                      477
#define IDB_TRAPDOOR                    479
#define IDB_TSHIELD                     482
#define IDB_STAR                        484
#define IDB_ROCK                        486
#define IDB_NSHIELD                     489
#define IDB_MISSLE40                    491
#define IDB_MISSLE39                    493
#define IDB_MISSLE38                    495
#define IDB_MISSLE37                    497
#define IDB_MISSLE36                    499
#define IDB_MISSLE35                    501
#define IDB_MISSLE34                    503
#define IDB_MISSLE33                    505
#define IDB_MISSLE32                    507
#define IDB_MISSLE31                    509
#define IDB_MISSLE30                    511
#define IDB_MISSLE29                    513
#define IDB_MISSLE28                    515
#define IDB_MISSLE27                    517
#define IDB_MISSLE26                    519
#define IDB_MISSLE25                    521
#define IDB_HUGGER6B                    525
#define IDB_HUGGER6                     527
#define IDB_HUGGER5                     529
#define IDB_HUGGER4B                    531
#define IDB_HUGGER4                     533
#define IDB_HUGGER3                     535
#define IDB_HUGGER2                     537
#define IDB_HUGGER1B                    539
#define IDB_HUGGER17B                   542
#define IDB_HUGGER17                    544
#define IDB_HUGGER16B                   546
#define IDB_HUGGER16                    548
#define IDB_HUGGER15                    550
#define IDB_HUGGER12B                   552
#define IDB_HUGGER12                    554
#define IDB_HUGGER1                     555
#define IDB_HUGGER0B                    557
#define IDB_HUGGER0                     559
#define IDB_GRENADE1                    560
#define IDB_GRENADE2                    561
#define IDB_GRENADE3                    562
#define IDB_GRENADE4                    563
#define IDB_FROG_SHELL                  568
#define IDB_FROG_SHELLB                 569
#define IDB_FROG3                       572
#define IDB_FROG4                       573
#define IDB_FROG5                       574
#define IDB_FROG_DEAD                   575
#define IDB_FROG2                       581
#define IDB_FROG1                       583
#define IDB_FROG0                       585
#define IDB_STARB                       588
#define IDB_HERO10B                     628
#define IDB_HERO10                      632
#define IDB_HHERO0_ATTACK               640
#define IDB_HUGGER_DEAD                 643
#define IDB_CHAINSAW5B                  645
#define IDB_CHAINSAW5                   647
#define IDB_CHAINSAW37B                 649
#define IDB_CHAINSAW37                  651
#define IDB_CHAINSAW33B                 653
#define IDB_CHAINSAW33                  655
#define IDB_CHAINSAW29B                 657
#define IDB_CHAINSAW29                  659
#define IDB_CHAINSAW25B                 661
#define IDB_CHAINSAW25                  663
#define IDB_WALKER18B                   665
#define ID_XEVIL                        666
#define IDB_WALKER18                    667
#define IDB_HUGGER_RED_DEAD             669
#define ID_STATBACKDROP                 669
#define ID_HEALTHBAR                    670
#define IDB_HUGGER_RED6B                671
#define ID_MASSBAR                      671
#define ID_AMMOBAR                      672
#define IDB_HUGGER_RED6                 673
#define ID_WEAPONBAR                    673
#define ID_ITEMBAR                      674
#define IDB_HUGGER_RED5                 675
#define ID_MACHKILLSBAR                 675
#define ID_HUMANKILLSBAR                676
#define IDB_HUGGER_RED4B                677
#define ID_XTRALIVESBAR                 677
#define IDB_HUGGER_RED4                 679
#define IDB_HUGGER_RED3                 681
#define IDB_HUGGER_RED2                 683
#define IDB_HUGGER_RED1B                685
#define IDB_HUGGER_RED17B               688
#define IDB_HUGGER_RED17                690
#define IDB_HUGGER_RED16B               692
#define IDB_HUGGER_RED16                694
#define IDB_HUGGER_RED15                696
#define IDB_HUGGER_RED12B               698
#define IDB_HUGGER_RED12                700
#define IDB_HUGGER_RED1                 701
#define IDB_HUGGER_RED0B                703
#define IDB_HUGGER_RED0                 705
#define IDB_FLAME                       706
#define IDB_FIREBALL                    706
#define IDB_NINJA_DEAD                  709
#define IDB_NINJA8_ATTACK               710
#define IDB_NINJA7_ATTACK               711
#define IDB_NINJA6B                     713
#define IDB_NINJA6                      715
#define IDB_NINJA5                      716
#define IDB_NINJA4                      718
#define IDB_NINJA3D                     719
#define IDB_NINJA3C                     721
#define IDB_NINJA3_ATTACK               724
#define IDB_NINJA2D                     726
#define IDB_NINJA2C                     728
#define IDB_NINJA2B                     730
#define IDB_NINJA2_ATTACK               733
#define IDB_NINJA22_ATTACK              735
#define IDB_NINJA21_ATTACK              737
#define IDB_NINJA2                      738
#define IDB_NINJA1D                     740
#define IDB_NINJA1C                     742
#define IDB_NINJA1B                     744
#define IDB_NINJA1_ATTACK               747
#define IDB_NINJA19                     749
#define IDB_NINJA18B                    751
#define IDB_NINJA18                     753
#define IDB_NINJA17B                    755
#define IDB_NINJA17_ATTACK              758
#define IDB_NINJA17                     759
#define IDB_NINJA16B                    761
#define IDB_NINJA16_ATTACK              764
#define IDB_NINJA16                     765
#define IDB_NINJA14_ATTACK              767
#define IDB_NINJA13_ATTACK              769
#define IDB_NINJA12B                    771
#define IDB_NINJA12                     773
#define IDB_NINJA11B                    775
#define IDB_NINJA11_ATTACK              778
#define IDB_NINJA11                     779
#define IDB_NINJA10B                    781
#define IDB_NINJA10_ATTACK              784
#define IDB_NINJA10                     785
#define IDB_NINJA1                      786
#define IDB_NINJA0D                     788
#define IDB_NINJA0C                     790
#define IDB_NINJA0B                     792
#define IDB_NINJA0_ATTACK               795
#define IDB_NINJA0                      796
#define IDB_MISSLE40B                   797
#define IDB_MISSLE39B                   798
#define IDB_MISSLE38B                   799
#define IDB_MISSLE37B                   800
#define IDB_MISSLE36B                   801
#define IDB_MISSLE35B                   802
#define IDB_MISSLE34B                   803
#define IDB_MISSLE33B                   804
#define IDB_MISSLE32B                   805
#define IDB_MISSLE31B                   806
#define IDB_MISSLE30B                   807
#define IDB_MISSLE29B                   808
#define IDB_MISSLE28B                   809
#define IDB_MISSLE27B                   810
#define IDB_MISSLE26B                   811
#define IDB_MISSLE25B                   812
#define IDD_SNDDRIVER                   815
#define IDW_CHAINSAW_SOUND              818
#define IDW_FLAMETHROWER                819
#define IDW_DEATH                       820
#define IDW_SEAL_DEATH                  821
#define IDW_HUGGER_DEATH                822
#define IDW_FROG_DEATH                  823
#define IDW_SOUNDTRACK                  824
#define IDW_BREAKDOWN                   826
#define IDW_BANG                        827
#define IDP_XEVILPALETTE                828
#define IDB_CHOPPERBOY3B                829
#define IDB_CHOPPERBOY2B                830
#define IDW_SOUNDTRACK_SEAL             830
#define IDW_SOUNDTRACK_LEVELS           831
#define IDB_DOPPEL2                     831
#define IDW_PISTOL                      832
#define IDB_CLOAK2                      832
#define IDB_CLOAKC                      832
#define IDW_MGUN                        833
#define IDB_MAGICBLOCK                  833
#define IDW_LAUNCHER                    834
#define IDB_WINNERS_DRUGS               834
#define IDW_EXPLOSION                   835
#define IDB_TAKE_CANDY                  836
#define IDB_STRANGLE_CAT                837
#define IDD_TIMESTAMPFAILED             837
#define IDB_SQUANCH_BIG                 838
#define IDB_SKULL                       839
#define IDD_KEYS                        839
#define IDB_PYRAMID                     840
#define IDB_PENT                        841
#define IDB_NICE_DAY                    842
#define IDB_KILL_PARENTS                843
#define IDB_FIST                        844
#define IDB_DROP_SCHOOL                 845
#define IDB_BEAT_DOG                    846
#define IDB_BCEAGLE                     847
#define IDB_CHOPPERBOY4B                848
#define IDB_DOG_DEAD                    849
#define IDB_DOG9                        850
#define IDB_DOG5                        851
#define IDB_DOG4                        852
#define IDB_DOG22                       852
#define IDB_DOG3_ATTACK                 853
#define IDB_DOG3                        854
#define IDB_DOG2_ATTACK                 855
#define IDB_DOG22_ATTACK                856
#define IDB_DOG21_ATTACK                857
#define IDB_DOG20B                      858
#define IDB_DOG20                       859
#define IDB_DOG2                        860
#define IDB_DOG1B                       861
#define IDB_DOG1_ATTACK                 862
#define IDB_DOG18                       863
#define IDB_DOG11B                      864
#define IDB_DOG11_ATTACK                865
#define IDB_DOG11                       866
#define IDB_DOG10B                      867
#define IDB_DOG10_ATTACK                868
#define IDB_DOG10                       869
#define IDB_DOG1                        870
#define IDB_DOG0B                       871
#define IDB_DOG0_ATTACK                 872
#define IDB_DOG0                        873
#define IDB_DOGWHISTLE                  874
#define IDD_WEAPONLIST                  875
#define IDB_MOVER                       876
#define IDB_MOVERSQUARE                 877
#define IDW_DOG_DEATH                   877
#define IDB_VERTMOVERSQUARE             877
#define IDW_LASER                       878
#define IDW_HERO_ATTACK                 879
#define IDW_NINJA_ATTACK                880
#define IDW_DOG_ATTACK                  881
#define IDW_CHOP_DEATH                  882
#define IDW_DOPPEL_USE                  883
#define IDW_CLOAK_USE                   884
#define IDW_TRANS_USE                   885
#define IDW_SHIELD_USE                  886
#define IDW_NINJA_DEATH                 887
#define IDW_FROGGUN                     888
#define IDW_LANCER                      889
#define IDW_SWAPPER                     890
#define IDB_DOG21                       893
#define IDB_CRACKPIPE                   894
#define IDB_BLOODG6                     939
#define IDB_BLOODG9                     940
#define IDB_BACKGROUND                  953
#define IDB_BACKGROUND2                 954
#define IDB_BACKGROUND3                 955
#define IDB_LAUNCHER1                   958
#define IDB_LAUNCHER2                   959
#define IDB_LAUNCHER3                   960
#define IDB_LAUNCHER4                   961
#define IDB_LAUNCHER5                   962
#define IDB_LAUNCHER6                   963
#define IDB_LAUNCHER7                   964
#define IDB_LAUNCHER8                   965
#define IDB_LAUNCHER9                   966
#define IDB_LAUNCHER10                  967
#define IDB_LAUNCHER11                  968
#define IDB_LAUNCHER12                  969
#define IDB_BACKGROUND4                 972
#define IDB_BACKGROUND5                 973
#define IDB_WALL1                       975
#define IDB_WALL2                       975
#define IDB_OUTSIDE3                    978
#define IDB_PISTOL1                     979
#define IDB_OUTSIDE4                    980
#define IDB_UPDOWN2                     981
#define IDB_LADDER2                     982
#define IDB_MOVERSQUARE2                983
#define IDB_MOVER2                      984
#define IDB_OIL12                       985
#define IDB_OIL15                       986
#define IDB_OIL25                       987
#define IDB_OIL26                       988
#define IDB_OIL27                       989
#define IDB_OIL28                       990
#define IDB_OIL29                       991
#define IDB_OIL30                       992
#define IDB_OIL31                       993
#define IDB_OIL32                       994
#define IDB_OIL33                       995
#define IDB_OIL34                       996
#define IDB_OIL35                       997
#define IDB_OIL36                       998
#define IDB_OIL37                       999
#define IDB_OIL38                       1000
#define IDB_OIL39                       1001
#define IDB_OIL4                        1002
#define IDB_OIL40                       1003
#define IDB_OIL6                        1004
#define IDB_OIL9                        1005
#define IDB_PISTOL9                     1006
#define IDB_PISTOL8                     1007
#define IDC_GAMESTYLE                   1008
#define IDB_PISTOL7                     1008
#define IDC_STYLESCENARIOS              1008
#define IDC_RADIO2                      1009
#define IDB_PISTOL6                     1009
#define IDC_GAMESTYLE2                  1009
#define IDC_OBSERVER                    1009
#define IDC_STYLELEVELS                 1009
#define IDC_NINEKEY                     1009
#define IDC_RADIO3                      1010
#define IDB_PISTOL5                     1010
#define IDC_RADIO4                      1011
#define IDB_PISTOL4                     1011
#define IDC_RADIO5                      1012
#define IDB_PISTOL3                     1012
#define IDC_STYLEDUEL                   1012
#define IDB_PISTOL2                     1013
#define IDB_PISTOL12                    1014
#define IDB_PISTOL11                    1015
#define IDB_PISTOL10                    1016
#define IDB_ROCKHI                      1017
#define IDC_NUMMACHINES                 1019
#define IDC_NUMHUMANS                   1020
#define IDC_RADIO1                      1021
#define IDC_STYLETRAINING               1021
#define IDC_FOURKEY                     1021
#define IDC_ROOMWIDTH                   1022
#define IDC_ROOMHEIGHT                  1023
#define IDC_TAB                         1024
#define IDC_COMBO1                      1025
#define IDC_SOUNDONOFF                  1026
#define IDB_BGALIEN                     1026
#define IDB_BGHELL2OLD                  1027
#define IDC_GAMESPEED                   1028
#define IDB_BGHELL3                     1028
#define IDB_BGINDUSTRIAL                1028
#define IDC_SOUNDTRACKVOL               1029
#define IDC_EFFECTVOL                   1030
#define IDB_ARROW_R                     1030
#define IDB_RARROW_R                    1030
#define IDB_BGHELL4                     1031
#define IDB_BGIND1                      1032
#define IDB_BGJESUS                     1033
#define IDC_FULLSCREEN                  1035
#define IDC_F5BUTTON                    1036
#define IDB_ARROW_UP                    1036
#define IDB_ARROW_L                     1037
#define IDB_ARROW_DN_R                  1038
#define IDB_ARROW_UP_R                  1039
#define IDB_RARROW_UP_R                 1039
#define IDB_ARROW_DN_L                  1040
#define IDC_DIFFICULTY1                 1040
#define IDB_ARROW_UP_L                  1041
#define IDC_DIFFICULTY2                 1041
#define IDC_SOUNDTYPE                   1044
#define IDC_RADIO8                      1046
#define IDC_RADIO9                      1047
#define IDC_RADIO10                     1048
#define IDC_UL                          1051
#define IDC_PLAYERSTATIC                1052
#define IDC_WEAPONUSE                   1053
#define IDC_COOPERATIVE                 1054
#define IDC_MYSTATIC                    1056
#define IDC_BUTTON1                     1058
#define IDC_EDIT1                       1059
#define IDC_EDIT2                       1060
#define IDC_EDIT3                       1061
#define IDC_PLAYER                      1062
#define IDB_BGHELL1                     1063
#define IDC_UP                          1066
#define IDC_UR                          1067
#define IDC_L                           1068
#define IDC_CENTER                      1069
#define IDC_R                           1070
#define IDB_ARROW_DN                    1071
#define IDC_LL                          1071
#define IDB_PEPPERORIG                  1072
#define IDC_DOWN                        1072
#define IDB_PILLS                       1073
#define IDC_LR                          1073
#define IDC_REFILLMACHINES              1073
#define IDC_WEAPONCHANGE                1074
#define IDC_STYLEKILL                   1074
#define IDB_HICHOPPERBOY0               1075
#define IDC_WEAPONDROP                  1075
#define IDC_STYLEEXTENDED               1075
#define IDB_HICHOPPERBOY0B              1076
#define IDC_ITEMUSE                     1076
#define IDC_DRAWBACKGROUND              1076
#define IDB_HICHOPPERBOY0C              1077
#define IDC_ITEMCHANGE                  1077
#define IDB_HICHOPPERBOY0D              1078
#define IDC_ITEMDROP                    1078
#define IDC_CHAT                        1079
#define IDB_HICHOPPERBOY0E              1080
#define IDC_VERSION                     1081
#define IDB_HICHOPPERBOY0F              1082
#define IDC_LICENSETEXT                 1082
#define IDB_HICHOPPERBOY1               1083
#define IDC_HUMAN                       1083
#define IDB_HICHOPPERBOY1B              1084
#define IDB_HICHOPPERBOY1C              1085
#define IDB_HICHOPPERBOY1D              1086
#define IDB_HICHOPPERBOY1E              1087
#define IDB_HICHOPPERBOY1F              1088
#define IDB_HICHOPPERBOY2               1089
#define IDB_HICHOPPERBOY2B              1090
#define IDB_HICHOPPERBOY2C              1091
#define IDB_HICHOPPERBOY2D              1092
#define IDB_HICHOPPERBOY3               1093
#define IDB_HICHOPPERBOY3B              1094
#define IDB_HICHOPPERBOY3C              1095
#define IDB_HICHOPPERBOY3D              1096
#define IDB_HICHOPPERBOY25              1097
#define IDB_HICHOPPERBOY4               1098
#define IDB_HICHOPPERBOY4B              1099
#define IDB_HICHOPPERBOY4C              1100
#define IDB_HICHOPPERBOY4D              1101
#define IDB_HICHOPPERBOY5               1102
#define IDB_WALL3                       1103
#define IDB_NEWPISTOL0                  1106
#define IDB_NEWPISTOL1                  1107
#define IDB_NEWPISTOL2                  1108
#define IDB_NEWPISTOL3                  1109
#define IDB_NEWPISTOL4                  1110
#define IDB_NEWPISTOL5                  1111
#define IDB_NEWPISTOL6                  1112
#define IDB_NEWPISTOL7                  1113
#define IDB_NEWPISTOL8                  1114
#define IDB_NEWPISTOL9                  1115
#define IDB_NEWPISTOL10                 1116
#define IDB_NEWPISTOL11                 1117
#define IDB_NEWLAUNCHER0                1118
#define IDB_NEWLAUNCHER1                1119
#define IDB_NEWLAUNCHER2                1120
#define IDB_NEWLAUNCHER3                1121
#define IDB_NEWLAUNCHER4                1122
#define IDB_NEWLAUNCHER5                1123
#define IDB_NEWLAUNCHER6                1124
#define IDB_NEWLAUNCHER7                1125
#define IDB_NEWLAUNCHER8                1126
#define IDB_NEWLAUNCHER9                1127
#define IDB_NEWLAUNCHER10               1128
#define IDB_NEWLAUNCHER11               1129
#define IDB_CAFFINE                     1130
#define IDB_HIWALL                      1132
#define IDB_HORIZMOVERSQUARE            1133
#define IDB_HIWALL2                     1135
#define IDB_HILADDER2                   1136
#define IDB_HIUPDOWN                    1137
#define IDB_HIDOOR1                     1138
#define IDB_HIDOOR2                     1139
#define IDB_HIOUTSIDE                   1140
#define IDB_BGALIENNU                   1141
#define IDB_BGHELL2                     1142
#define IDB_HICHOPPERBOY22              1143
#define IDB_HICHOPPERBOY22B             1144
#define IDB_HICHOPPERBOY22C             1145
#define IDB_HICHOPPERBOY22D             1146
#define IDD_DIFFICULTY                  1147
#define IDB_HIER1                       1148
#define IDB_HIERBLOK                    1149
#define IDB_BITMAP1                     1150
#define IDB_HIOUTSIDE1                  1151
#define IDB_HIOUTSIDE2                  1152
#define IDB_HILADDER                    1153
#define IDB_BITMAP2                     1154
#define IDB_HIHERO0                     1155
#define IDB_HIHERO0F                    1156
#define IDB_HIHERO0C                    1157
#define IDB_HIHERO0D                    1158
#define IDB_HIHERO0E                    1159
#define IDB_HIHERO0B                    1160
#define IDB_HIHERO5                     1161
#define IDB_HHERO5                      1161
#define IDB_HIHERO1                     1162
#define IDB_HIHERO1B                    1163
#define IDB_HIHERO1C                    1164
#define IDB_HIHERO1D                    1165
#define IDB_HIHERO1E                    1166
#define IDB_HIHERO1F                    1167
#define IDD_KEYSETS                     1168
#define IDB_YARROW_UP_R                 1197
#define IDB_YARROW_UP_L                 1198
#define IDB_YARROW_UP                   1199
#define IDB_YARROW_R                    1200
#define IDB_YARROW_L                    1201
#define IDB_YARROW_DN_R                 1202
#define IDB_YARROW_DN_L                 1203
#define IDB_YARROW_DN                   1204
#define IDB_GARROW_UP_R                 1205
#define IDB_GARROW_UP_L                 1206
#define IDB_GARROW_UP                   1207
#define IDB_GARROW_R                    1208
#define IDB_GARROW_L                    1209
#define IDB_GARROW_DN_R                 1210
#define IDB_GARROW_DN_L                 1211
#define IDB_GARROW_DN                   1212
#define IDB_HIALTAR                     1216
#define IDB_HIALTARB                    1217
#define IDB_HHERO0                      1218
#define IDB_HHERO0F                     1219
#define IDB_HHERO0C                     1220
#define IDB_HHERO0D                     1221
#define IDB_HHERO0E                     1222
#define IDB_HHERO0B                     1223
#define IDI_ICON1                       1230
#define IDB_BARROW_UP_R                 1230
#define IDB_BARROW_UP_L                 1231
#define IDB_BARROW_UP                   1232
#define IDB_BARROW_R                    1233
#define IDB_BARROW_L                    1234
#define IDB_BARROW_DN_R                 1235
#define IDB_BARROW_DN_L                 1236
#define IDB_BARROW_DN                   1237
#define IDB_HITSHIELD                   1239
#define IDB_HINSHIELD                   1240
#define IDB_HIWEIGHT                    1241
#define IDB_HIERUPDOWN                  1242
#define IDB_HIERBLOK2                   1243
#define IDB_HICHOPPERBOY21D             1244
#define IDB_HICHOPPERBOY21B             1245
#define IDB_HICHOPPERBOY21C             1246
#define IDB_HICHOPPERBOY21              1247
#define IDB_HIMEDKIT                    1266
#define IDB_HIALTARC                    1269
#define IDR_XEVILPAL                    1270
#define IDB_TEST                        1271
#define IDD_KEYHIT                      1272
#define IDB_LOGOB4                      1273
#define IDB_DISPLAYBITMAP               1274
#define IDB_WHEELBACKGROUND             1274
#define IDB_NAPALMS                     1275
#define IDB_NAPALM1                     1276
#define IDB_NAPALM2                     1277
#define IDB_NAPALM3                     1278
#define IDB_NAPALM4                     1279
#define IDB_HHERO0B_ATTACK              1282
#define IDB_HHERO10_ATTACK              1288
#define IDB_HHERO10B_ATTACK             1289
#define IDB_HHERO2                      1290
#define IDB_HIDOG0B                     1292
#define IDB_HIDOG0                      1293
#define IDB_HIDOG0_ATTACK               1296
#define IDB_HIDOG1_ATTACK               1297
#define IDB_HIDOG0_TONGUE               1298
#define IDB_HININJA5                    1301
#define IDB_HININJA1F                   1302
#define IDB_HININJA0B                   1303
#define IDB_HININJA0C                   1304
#define IDB_HININJA0D                   1305
#define IDB_HININJA0E                   1306
#define IDB_HININJA0F                   1307
#define IDB_HININJA1                    1308
#define IDB_HININJA1B                   1309
#define IDB_HININJA1C                   1310
#define IDB_HININJA1D                   1311
#define IDB_HININJA1E                   1312
#define IDB_HININJA0                    1313
#define IDB_HIENFORCER1B                1314
#define IDB_HIENFORCER0B                1315
#define IDB_HIENFORCER1                 1316
#define IDB_HIENFORCER0                 1317
#define IDB_SEALDEAD                    1318
#define IDB_HIHOMEB                     1319
#define IDB_HIHOMEC                     1320
#define IDB_HITRAPDOOR                  1321
#define IDB_SEAL0                       1322
#define IDB_SEAL0B                      1323
#define IDB_SEAL1                       1324
#define IDB_SEAL1B                      1325
#define IDB_SEAL5                       1326
#define IDB_HIHOME                      1327
#define IDB_HIDOG22_ATTACK              1328
#define IDB_HIDOG21_ATTACK              1329
#define IDB_HIDOG2_ATTACK               1330
#define IDB_HIDOG3_ATTACK               1331
#define IDB_HIDOG5B                     1332
#define IDB_HIDOG5                      1333
#define IDB_HIDOG21                     1334
#define IDB_HIDOG22                     1335
#define IDB_HIDOGDEAD                   1336
#define IDB_HIDOG21B                    1337
#define IDB_HIDOG22B                    1338
#define IDB_HIDOG2                      1339
#define IDB_HIDOG3                      1340
#define IDB_LOGOB5                      1341
#define IDB_TITLE                       1341
#define IDB_HITEXTSQUARE                1342
#define IDB_LANCER1                     1343
#define IDB_HIBOMB0                     1344
#define IDB_HIBOMB1                     1345
#define IDB_HIBOMB2                     1346
#define IDB_HIBOMB3                     1347
#define IDB_HIBOMB4                     1348
#define IDB_HIBOMB5                     1349
#define IDB_HIBOMB6                     1350
#define IDB_HIBOMBBLK                   1351
#define IDB_HIPISTOL                    1352
#define IDB_HILAUNCHER                  1353
#define IDB_MGUN1                       1354
#define IDB_NONE                        1355
#define IDB_LASERS                      1356
#define IDB_CLOAK1                      1357
#define IDB_CLOAKB                      1357
#define IDB_CLOAK3                      1358
#define IDB_CLOAKD                      1358
#define IDB_CLOAK4                      1359
#define IDB_CLOAKE                      1359
#define IDB_CLOAK5                      1360
#define IDB_CLOAKF                      1360
#define IDB_FLAME2                      1361
#define IDB_FIREBALLB                   1361
#define IDB_FLAME3                      1362
#define IDB_FIREBALLC                   1362
#define IDB_ENFORCER0C                  1365
#define IDB_ENFORCER0A                  1366
#define IDB_ENFORCER1C                  1370
#define IDB_ENFORCER1A                  1371
#define IDB_HIHERO4                     1372
#define IDB_HHERO4                      1372
#define IDB_HIHERO2_ATTACK              1373
#define IDB_HHERO2_ATTACK               1373
#define IDB_HIHERO3_ATTACK              1374
#define IDB_HIHERO10                    1375
#define IDB_HIHERO10B                   1376
#define IDB_CHAINSAW25C                 1377
#define IDB_CHAINSAW33C                 1378
#define IDB_HIHERO22_ATTACK             1379
#define IDB_HHERO22_ATTACK              1379
#define IDB_HIHERO21_ATTACK             1380
#define IDB_HININJA3D                   1381
#define IDB_HIHERO20                    1382
#define IDB_HIHERO20B                   1385
#define IDB_HIHERO19                    1386
#define IDB_HHERO18                     1386
#define IDB_HININJA_DEAD                1399
#define IDB_HININJA2                    1400
#define IDB_HININJA2B                   1401
#define IDB_HININJA2C                   1402
#define IDB_HININJA2D                   1403
#define IDB_HININJA3                    1404
#define IDB_HININJA3B                   1405
#define IDB_HININJA3C                   1406
#define IDB_HIHERO_DEAD                 1407
#define IDB_HHERO_DEAD                  1407
#define IDB_HIENFORCER_DEAD             1408
#define IDB_HIWALKER18B                 1410
#define IDB_HIWALKER0B                  1411
#define IDB_HIWALKER0C                  1412
#define IDB_DRAGONBODY                  1413
#define IDB_HIWALKER0D                  1414
#define IDB_DRAGONHEAD                  1415
#define IDB_DRAGONDEAD                  1416
#define IDB_HIWALKER2                   1417
#define IDB_HIWALKER_DEAD               1418
#define IDB_HIWALKER18                  1419
#define IDB_HIWALKER2B                  1420
#define IDB_HIWALKER4                   1421
#define IDB_HIWALKER4B                  1422
#define IDB_HIWALKER4C                  1423
#define IDB_HIWALKER4D                  1424
#define IDB_HIWALKER5                   1425
#define IDB_HIWALKER5B                  1426
#define IDB_HIWALKER5C                  1427
#define IDB_HIWALKER5D                  1428
#define IDB_HIWALKER0                   1429
#define IDB_HIWALKER3                   1430
#define IDB_HIWALKER3B                  1431
#define IDB_HIWALKER1                   1432
#define IDB_HIWALKER1B                  1433
#define IDB_HIWALKER1C                  1434
#define IDB_HIWALKER1D                  1435
#define IDD_CONNECTSERVER               1436
#define IDB_HIFIREDEMON5B               1436
#define IDD_RUNSERVER                   1437
#define IDB_HIFIREDEMON5                1437
#define IDB_XEVIL                       1438
#define IDB_STOP                        1439
#define IDB_HIFIREDEMON22               1440
#define IDB_HANDTOHAND                  1441
#define IDB_HIFIREDEMON0                1442
#define IDB_HIFIREDEMON0B               1443
#define IDB_HIFIREDEMON1                1444
#define IDB_HIFIREDEMON1B               1445
#define IDB_HIFIREDEMON_DEAD            1446
#define IDB_HIFIREDEMON4                1447
#define IDB_HIFIREDEMON3                1448
#define IDB_HIFIREDEMON2                1449
#define IDB_HININJA22_ATTACK            1454
#define IDB_HININJA0_ATTACK             1455
#define IDB_HININJA3_ATTACK             1456
#define IDB_HININJA1_ATTACK             1457
#define IDB_HININJA2_ATTACK             1458
#define IDB_HININJA22                   1459
#define IDB_HININJA22B                  1460
#define IDB_HININJA21                   1461
#define IDB_HIFLAG                      1462
#define IDB_DROPLIFTABLE                1463
#define IDB_SUICIDEBUTTON               1464
#define IDB_FIREBALLICON                1465
#define IDB_FIRE                        1466
#define IDD_STORY                       1466
#define IDB_HIHUGGER_RED0               1470
#define IDB_HIHUGGER_RED0B              1472
#define IDB_HIHUGGER_RED5               1474
#define IDB_HIHUGGER_RED4               1476
#define IDB_HININJA10B                  1478
#define IDB_HININJA10                   1480
#define IDB_HININJA11F                  1482
#define IDB_HININJA10C                  1484
#define IDB_HIHUGGER_RED_DEAD           1485
#define IDB_HININJA10D                  1486
#define IDB_HININJA10F                  1487
#define IDB_HININJA11C                  1490
#define IDB_HIHUGGER_RED1               1491
#define IDB_HIHUGGER_RED1B              1492
#define IDB_HIHUGGER_RED12              1493
#define IDB_HIHUGGER_RED12B             1494
#define IDB_HIHUGGER_RED15              1495
#define IDB_HIHUGGER_RED16              1496
#define IDB_HIHUGGER_RED16B             1497
#define IDB_HIHUGGER_RED17              1498
#define IDB_HIHUGGER_RED17B             1499
#define IDB_HIHUGGER_RED6               1500
#define IDB_HIHUGGER_RED6B              1501
#define IDB_HIHUGGER_RED4B              1502
#define IDB_PRICKLY                     1503
#define IDB_HININJA11B                  1505
#define IDB_UNUSEDBLOCK                 1506
#define IDB_HININJA11D                  1507
#define IDB_HININJA11E                  1508
#define IDB_HININJA10E                  1510
#define IDB_HININJA10_ATTACK            1511
#define IDB_HININJA11_ATTACK            1512
#define IDB_HININJA21_ATTACK            1513
#define IDB_HIHUGGER_GREEN0             1514
#define IDB_HIHUGGER_GREEN0B            1515
#define IDB_HIHUGGER_GREEN4             1516
#define IDB_HIHUGGER_GREEN4B            1517
#define IDB_HIHUGGER_GREEN5             1518
#define IDB_HIHUGGER_GREEN6             1519
#define IDB_HIHUGGER_GREEN6B            1520
#define IDB_HIHUGGER_GREEN_DEAD         1521
#define IDB_MDWALL                      1522
#define IDB_MD1WALL                     1522
#define IDB_MDDOOR1                     1523
#define IDB_MD1DOOR1                    1523
#define IDB_MDLADDER                    1524
#define IDB_MD1LADDER                   1524
#define IDB_MDMOVER                     1525
#define IDB_MD1MOVER                    1525
#define IDB_MDVERTMOVERSQUARE           1526
#define IDB_MD1VERTMOVERSQUARE          1526
#define IDB_MDOUTSIDE                   1527
#define IDB_MD1OUTSIDE                  1527
#define IDB_MDUPDOWN                    1528
#define IDB_MD1UPDOWN                   1528
#define IDB_MDDOOR2                     1529
#define IDB_MD1DOOR2                    1529
#define IDB_MDHORIZMOVERSQUARE          1530
#define IDB_MD1HORIZMOVERSQUARE         1530
#define IDB_BLACK                       1531
#define IDB_MDBACKGROUND                1532
#define IDB_MD1BACKGROUND               1532
#define IDB_HININJA18                   1533
#define IDB_MD2WALL                     1534
#define IDB_MD2DOOR2                    1535
#define IDB_MD2DOOR1                    1536
#define IDB_MD2HORIZMOVERSQUARE         1537
#define IDB_HININJA18B                  1538
#define IDB_AUTOLANCER                  1539
#define IDB_DEMONSUMMONER               1540
#define IDB_MD2LADDER                   1541
#define IDB_HIDDOG0                     1542
#define IDB_HIDDOG0_ATTACK              1543
#define IDB_HIDDOG21_ATTACK             1544
#define IDB_HIDDOG22_ATTACK             1545
#define IDB_HIDDOG2_ATTACK              1546
#define IDB_HIDDOG0B                    1547
#define IDB_HIDDOG2                     1548
#define IDB_HIDDOG21                    1549
#define IDB_HIDDOG21B                   1550
#define IDB_HIDDOG22                    1551
#define IDB_HIDDOG22B                   1552
#define IDB_HIDDOG5                     1553
#define IDB_HIDDOG5B                    1554
#define IDB_HIDDOGDEAD                  1555
#define IDB_MDBACKGROUND1               1556
#define IDB_MD2MOVER                    1557
#define IDB_MD2OUTSIDE1                 1558
#define IDB_MD2OUTSIDE2                 1559
#define IDB_MD2UPDOWN                   1560
#define IDB_MD2VERTMOVERSQUARE          1561
#define IDB_MD2BACKGROUND               1562
#define IDB_SERVEROPTIONS               1563
#define IDB_MENUNEWGAME                 1565
#define IDB_DRAGONHEADC                 1568
#define IDB_DRAGONHEADB                 1569
#define IDB_DRAGONHEADD                 1572
#define IDB_MD3OUTSIDE                  1578
#define IDB_MD3MOVER                    1579
#define IDB_MD3BACKGROUND               1580
#define IDB_HIALIEN0I                   1582
#define IDB_HIALIEN10B                  1583
#define IDB_HIALIEN10C                  1584
#define IDB_HIALIEN10D                  1585
#define IDB_HIALIEN0                    1586
#define IDB_HIALIEN0B                   1587
#define IDB_HIALIEN0C                   1588
#define IDB_HIALIEN0G                   1592
#define IDB_HIALIEN0H                   1593
#define IDB_HIALIEN10                   1594
#define IDB_TROLL5                      1595
#define IDB_YETI5                       1595
#define IDB_TROLL0B                     1596
#define IDB_YETI0B                      1596
#define IDB_TROLL0C                     1597
#define IDB_YETI0C                      1597
#define IDB_TROLL0D                     1598
#define IDB_YETI0D                      1598
#define IDB_TROLL2                      1599
#define IDB_YETI2                       1599
#define IDB_TROLL0                      1600
#define IDB_YETI0                       1600
#define IDB_TROLL1                      1601
#define IDB_TROLL25                     1601
#define IDB_YETI25                      1601
#define IDB_TROLL18                     1602
#define IDB_YETI18                      1602
#define IDB_TROLL18B                    1603
#define IDB_YETI18B                     1603
#define IDB_HIALIEN2                    1604
#define IDB_HIALIEN5                    1605
#define IDB_HIALIEN18                   1606
#define IDB_HIALIEN18B                  1607
#define IDB_HIALIEN18C                  1608
#define IDB_HIALIEN18D                  1609
#define IDB_HIALIEN25                   1610
#define IDB_TROLL4                      1611
#define IDB_YETI4                       1611
#define IDB_AAANEW                      1612
#define IDB_ZOMBIE0                     1612
#define IDB_MD3WALL                     1613
#define IDB_MD3LADDER                   1614
#define IDB_MD3UPDOWN                   1615
#define IDB_MD3DOOR1                    1618
#define IDB_MD3DOOR2                    1619
#define IDB_MD3HORIZMOVERSQUARE         1620
#define IDB_MD3VERTMOVERSQUARE          1621
#define IDB_TROLL9                      1623
#define IDB_YETI9                       1623
#define IDB_TROLL10F                    1624
#define IDB_YETI10F                     1624
#define IDB_TROLL10B                    1625
#define IDB_YETI10B                     1625
#define IDB_TROLL10C                    1626
#define IDB_YETI10C                     1626
#define IDB_TROLL10D                    1627
#define IDB_YETI10D                     1627
#define IDB_TROLL10E                    1628
#define IDB_YETI10E                     1628
#define IDB_TROLL10                     1629
#define IDB_YETI10                      1629
#define IDB_MD2OUTSIDE                  1630
#define IDM_SEALSOUNDTRACK              1630
#define IDM_DEATHMARCHSOUNDTRACK        1631
#define IDB_MD4WALL                     1631
#define IDM_FIRESOUNDTRACK              1632
#define IDB_MD4BACKGROUND               1632
#define IDM_HIVESOUNDTRACK              1633
#define IDB_MD4DOOR1                    1633
#define IDM_KKKSOUNDTRACK               1634
#define IDM_KILLSOUNDTRACK              1634
#define IDB_MD4HORIZMOVERSQUARE         1634
#define IDM_ZEEPEEGSOUNDTRACK           1635
#define IDB_MD4OUTSIDE                  1635
#define IDM_NIGHTSKYSOUNDTRACK          1636
#define IDB_MD4UPDOWN                   1636
#define IDM_SWEETDARKSOUNDTRACK         1637
#define IDB_MD4LADDER                   1637
#define IDM_TERRAEXMSOUNDTRACK          1638
#define IDB_MD4DOOR2                    1638
#define IDM_NEWSONGSOUNDTRACK           1639
#define IDB_MD4VERTMOVERSQUARE          1639
#define IDB_MD4MOVER                    1640
#define IDB_HIALIEN0D                   1647
#define IDB_HIALIEN0E                   1648
#define IDB_HIALIEN0F                   1650
#define IDB_HIALIEN4                    1651
#define IDB_FWBACKGROUND1               1652
#define IDB_FWBACKGROUND2               1653
#define IDB_FWBACKGROUND3               1654
#define IDB_FWBACKGROUND4               1655
#define IDB_HININJA21_ATTACK2           1656
#define IDB_HHERO21_ATTACK2             1657
#define IDB_HININJA_18                  1658
#define IDB_HININJA_18B                 1659
#define IDB_HININJA_18C                 1660
#define IDB_HININJA_18D                 1661
#define IDB_HININJA_18E                 1662
#define IDB_HININJA_18F                 1663
#define IDB_HHERO18B                    1664
#define IDB_HHERO18C                    1665
#define IDB_HHERO18D                    1667
#define IDB_HHERO18E                    1668
#define IDB_HHERO18F                    1669
#define IDB_XIT                         1670
#define IDB_BLOOD25                     1671
#define IDB_BLOOD39                     1672
#define IDB_BLOOD4                      1673
#define IDB_BLOOD40                     1674
#define IDB_BLOOD9                      1675
#define IDB_BLOODG25                    1676
#define IDB_BLOODG39                    1677
#define IDB_BLOODG4                     1678
#define IDB_BLOODG40                    1679
#define IDB_LASER_HORIZ                 1680
#define IDB_VEGETABLES                  1682
#define IDB_AAANEW2                     1684
#define IDB_CHICKEN4                    1687
#define IDB_CHICKEN5                    1688
#define IDB_CHICKEN2_ATT                1689
#define IDB_CHICKEN21_ATT               1690
#define IDB_CHICKEN22_ATT               1691
#define IDB_CHICKENDEAD                 1695
#define IDB_CHICKEN2                    1696
#define IDB_CHICKEN2B                   1697
#define IDB_CHICKEN4B                   1698
#define IDB_CHICKEN0_ATT                1699
#define IDB_FEATHER25                   1700
#define IDB_FEATHER39                   1701
#define IDB_FEATHER40                   1702
#define IDB_FEATHER4                    1704
#define IDB_CHICKEN0                    1705
#define IDB_CHICKEN0B                   1706
#define IDB_CHICKEN0C                   1707
#define IDB_FEATHER9                    1708
#define IDB_MD5WALL                     1709
#define IDB_MD5OUTSIDE                  1710
#define IDB_MD5DOOR1                    1711
#define IDB_MD5DOOR2                    1712
#define IDB_MD5LADDER                   1717
#define IDB_MD5UPDOWN                   1718
#define IDB_MD5BACKGROUND               1719
#define IDB_ZOMBIE0B                    1720
#define IDB_ZOMBIE_DEAD                 1721
#define IDB_ZOMBIE10B                   1722
#define IDB_ZOMBIE10                    1723
#define IDB_ZOMBIE4                     1724
#define IDB_ZOMBIE2                     1725
#define IDB_ZOMBIE18                    1726
#define IDB_AAANEWW                     1727
#define IDB_ZOMBIE0C                    1728
#define IDB_ZOMBIE0F                    1729
#define IDB_ZOMBIE0E                    1730
#define IDB_ZOMBIE0D                    1731
#define IDB_ZOMBIE5                     1732
#define IDB_ZOMBIE18B                   1733
#define IDB_ZOMBIE18C                   1734
#define IDB_ZOMBIE18F                   1735
#define IDB_ZOMBIE18D                   1736
#define IDB_ZOMBIE18E                   1737
#define IDB_ZOMBIE0_ATTACK              1738
#define IDB_ZOMBIE22_ATTACK             1739
#define IDB_ZOMBIE21_ATTACK             1740
#define IDB_ZOMBIE10_ATTACK             1741
#define IDB_ZOMBIE2_ATTACK              1742
#define ID_GAME_KILL                    32771
#define ID_GAME_SCENARIO                32772
#define ID_NEWGAME                      32777
#define ID_OPTIONS                      32778
#define ID_KEYS                         32779
#define ID_FULLSCREEN                   32780
#define ID_WINDOWSCREEN                 32781
#define ID_KEYS2                        32783
#define ID_FOG                          32784
#define ID_GLOW                         32785
#define ID_DIFFICULTY                   32786
#define ID_CONNECTSERVER                32787
#define ID_RUNSERVER                    32788
#define ID_STORY                        32789
#define ID_NETHELP                      32790
#define ID_SURFACEMGR                   32791
#define ID_RESETGFX                     32792
#define IDC_NAMELABEL                   65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        1640
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           179
#endif
#endif
